apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-deployment
  labels:
    app: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-demo
  template:
    metadata:
      labels:
        app: microservices-demo
    spec:
      containers:
        - name: microservices-demo
          image: test.com/myimage
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256M
            limits:
              cpu: "1"
              memory: 1G
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 6
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 6
            timeoutSeconds: 10
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: microservices-demo-config